### ISSUE TITLE
automatic update of database

### ISSUE THREAD

**Issue by willmorrison1** [Urban-Meteorology-Reading/muhd-meta#10]
I have just updated the database on urban-climate.net/metadata. How/when will be changes be seen on the documentation?

Is [the database](https://github.com/Urban-Meteorology-Reading/muhd-meta/tree/main/metadata) automatically uploaded to the repo?

If not, I think it should. This could be the place where the database is backed up. 

Will

**Comment by kitbenjamin** [comment]
Not implimented yet but will be in the future. The with any changes to the metadata database, pages will be rewritten. I think it should be possible to automatically upload the metadata database but not 100% sure yet.

**Comment by kitbenjamin** [comment]
Added 7fbe03b73bd37b2e0545849f3a2e3eeca963bd61
