### ISSUE TITLE
deployments sub-section title 

### ISSUE THREAD

**Issue by willmorrison1** [Urban-Meteorology-Reading/muhd-meta#4]
add "serial number" text to sub-title.

change 
from: `s/n` 
to: "serial number: `s/n`"

e.g. 
![image](https://user-images.githubusercontent.com/51793934/101469423-a68cd300-393c-11eb-8ab6-defc94f6d3c8.png)

becomes: "3.19.7.1. Serial number: 120028"

**Comment by kitbenjamin** [comment]
Added
