### ISSUE TITLE
no immediate "help"

### ISSUE THREAD

**Issue by willmorrison1** [Urban-Meteorology-Reading/muhd-meta#6]
going to this link doesn't point me to the help page that you showed before?

![image](https://user-images.githubusercontent.com/51793934/101469870-2f0b7380-393d-11eb-9ff0-f7da168a9cca.png)

it is actually here https://muhd.readthedocs.io/en/latest/reference_guide/reference_guide.html but isn't found in help

**Comment by kitbenjamin** [comment]
Now redirected to [reference guide](https://muhd.readthedocs.io/en/latest/reference_guide/reference_guide.html#reference-guide)
