### ISSUE TITLE
site meta data table has NA header?

### ISSUE THREAD

**Issue by willmorrison1** [Urban-Meteorology-Reading/muhd-meta#8]
![image](https://user-images.githubusercontent.com/51793934/101470360-ce306b00-393d-11eb-8bf0-45e6e2c41418.png)

**Comment by kitbenjamin** [comment]
Replaced all NA with blank space - is this better?

![image](https://user-images.githubusercontent.com/53219529/101753268-5479b800-3aca-11eb-9900-a069c0d6d2c8.png)

**Comment by willmorrison1** [comment]
change columns from 1,2,3 to 1,3,2 (i.e. put units as last column)
