### ISSUE TITLE
"refused to connect" to something at top of LUMA network page

### ISSUE THREAD

**Issue by willmorrison1** [Urban-Meteorology-Reading/muhd-meta#9]
![image](https://user-images.githubusercontent.com/51793934/101470455-eef8c080-393d-11eb-9781-c206b06f4c50.png)

https://muhd.readthedocs.io/en/latest/networks/LUMA/LUMA.html

**Comment by kitbenjamin** [comment]
Now removed - will be a map of LUMA sites eventually

**Comment by suegrimmond** [comment]
map needed
